###############################################################################
# Created by write_sdc
###############################################################################
current_design riscv_core
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name core_clock -period 1.0000 [get_ports {clk}]
set_propagated_clock [get_clocks {core_clock}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[0]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[10]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[11]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[12]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[13]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[14]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[15]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[16]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[17]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[18]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[19]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[1]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[20]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[21]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[22]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[23]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[24]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[25]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[26]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[27]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[28]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[29]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[2]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[30]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[31]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[3]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[4]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[5]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[6]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[7]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[8]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {instr_in[9]}]
set_input_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {rst_n}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[0]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[10]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[11]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[12]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[13]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[14]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[15]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[16]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[17]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[18]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[19]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[1]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[20]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[21]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[22]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[23]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[24]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[25]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[26]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[27]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[28]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[29]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[2]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[30]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[31]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[3]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[4]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[5]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[6]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[7]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[8]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {alu_out_test[9]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[0]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[10]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[11]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[12]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[13]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[14]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[15]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[16]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[17]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[18]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[19]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[1]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[20]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[21]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[22]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[23]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[24]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[25]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[26]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[27]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[28]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[29]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[2]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[30]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[31]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[3]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[4]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[5]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[6]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[7]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[8]}]
set_output_delay 0.0500 -clock [get_clocks {core_clock}] -add_delay [get_ports {pc_out[9]}]
###############################################################################
# Environment
###############################################################################
###############################################################################
# Design Rules
###############################################################################
